--insert into product(product_name,product_price,product_stock,main_category_name,sub_category_name,content)values('토끼 애착인형',12000,150,'인형','동물인형','아기들이 좋아할만한 토끼 애착인형');
--insert into product(product_name,product_price,product_stock,main_category_name,sub_category_name,content)values('토끼 인형',15000,100,'인형','동물인형','아기들이 좋아할만한 토끼 애착인형');
--insert into product(product_name,product_price,product_stock,main_category_name,sub_category_name,content)values('강아지 애착인형',10000,120,'인형','동물인형','아기들이 좋아할만한 강아지 애착인형');
--insert into product(product_name,product_price,product_stock,main_category_name,sub_category_name,content)values('시나모롤 인형',15000,100,'인형','캐릭터인형','산리오 중 시나모롤 인형');
--insert into product(product_name,product_price,product_stock,main_category_name,sub_category_name,content)values('쿠로미 인형',15000,100,'인형','캐릭터인형','산리오 중 쿠로미 인형');
--insert into product(product_name,product_price,product_stock,main_category_name,sub_category_name,content)values('가족 인형',15000,100,'인형','사람인형','4인가족 인형이다');
--insert into product(product_name,product_price,product_stock,main_category_name,sub_category_name,content)values('유아용 물총',5000,500,'완구','실외장난감','아기들이 가지고 놀아도 안다치는 물총');
--insert into product(product_name,product_price,product_stock,main_category_name,sub_category_name,content)values('소꿉놀이 세트',20000,120,'완구','실외장난감','아기들이 좋아할만한 소꿉놀이세트');
--insert into product(product_name,product_price,product_stock,main_category_name,sub_category_name,content)values('해리포터 레고',30000,200,'완구','레고','해리포터를 배경으로 한 레고');
--insert into product(product_name,product_price,product_stock,main_category_name,sub_category_name,content)values('타요버스 촉각놀이세트',35000,180,'완구','촉각놀이','애니메이션 타요버스를 주제로한 촉각놀이 세트');
--insert into product(product_name,product_price,product_stock,main_category_name,sub_category_name,content)values('전래 동화 세트30권',50000,100,'도서','동화','한국의 전래 동화 추천 모음');
--insert into product(product_name,product_price,product_stock,main_category_name,sub_category_name,content)values('전래 동화 세트50권(Full)',70000,120,'도서','동화','한국의 전래 동화 전체 모음');
--insert into product(product_name,product_price,product_stock,main_category_name,sub_category_name,content)values('기초 영문 도서 세트',50000,200,'도서','영어도서','어릴때부터 접근하기 쉬운 영문 도서');
--insert into product(product_name,product_price,product_stock,main_category_name,sub_category_name,content)values('어린이 기초 영어 단어책',30000,200,'도서','영어도서','우리 아이 첫 영단어 배우기');
--insert into product(product_name,product_price,product_stock,main_category_name,sub_category_name,content)values('그림과 함께 읽는 동화책',20000,100,'도서','동화','그림으로 먼저 읽는 동화책');
--insert into product(product_name,product_price,product_stock,main_category_name,sub_category_name,content)values('영어로 시작하는 말하기',20000,200,'도서','영어도서','우리아이 말하기 영어로 시작해요');
--
--
